
import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    ClipboardCheck,
    Copy,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    LogIn,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    User,
    X,
    Home,
    ShoppingBag,
    Calendar,
    PenSquare,
    DollarSign,
    LayoutGrid,
    Users,
    MoreHorizontal,
  } from "lucide-react"
  
  export type Icon = typeof ChevronLeft
  
  export const Icons = {
    close: X,
    copy: Copy,
    login: LogIn,
    user: User,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    pizza: Pizza,
    spinner: Loader2,
    check: Check,
    help: HelpCircle,
    arrowRight: ArrowRight,
    home: Home,
    shop: ShoppingBag,
    bookings: Calendar,
    records: FileText,
    pcr: PenSquare,
    earnings: DollarSign,
    dashboard: LayoutGrid,
    patients: Users,
    more: MoreHorizontal,
    book: ClipboardCheck,
  }
  